build - Validate sshd_config
* Make sure the default sshd_config contains certain lines
  that we require.  At the moment, this adjustment makes sure
  that the sshd_config file has the correct PasswordAuthentication
  directive.

* Intended to catch snafus when openssh is updated from the vendor.

diff --git a/usr.sbin/sshd/Makefile.etc b/usr.sbin/sshd/Makefile.etc
--- a/usr.sbin/sshd/Makefile.etc
+++ b/usr.sbin/sshd/Makefile.etc
@@ -4,5 +4,13 @@ FILESMODE=	644
 FILESOWN=	${BINOWN}
 FILESGRP=	${BINGRP}
 
+# Make sure sshd_config disables PasswordAuthentication
+#
+beforeinstall:
+	@if [ "`(cat ${.CURDIR}/../../crypto/openssh/sshd_config | sort | uniq; cat ${.CURDIR}/sshd_config_expect) | sort | uniq -d | wc -l`" != "`cat ${.CURDIR}/sshd_config_expect | wc -l`" ]; then \
+		echo "crypto sshd_config missing expected directives"; \
+		exit 1;	\
+	fi
+
 .include "../../Makefile.ssh.common"
 .include <bsd.prog.mk>
