Change the default handling for kernels built with debugging info (DEBUG=-g). Since GENERIC includes this make option, this applies to most kernels.
Previously, installed kernels were stripped of their debug information and
installed modules were not.  With this commit, the debug info is left intact
in the installed kernel and debug information is stripped from all backup
copies that are made (kernel.old, modules.old).  Developers using DEBUG=-g
(which is most) may actually see root disk space go down due to the stripping
of kernel.old and modules.old (-~30MB), even though /kernel will be +~13MB
larger.

Two new makeoptions are available for specification in your kernel config or
when you run the buildkernel/nativekernel/installkernel target to make.

INSTALLSTRIPPED=1

    The installed kernel and modules will be stripped of debug info.  This
    option effectively reverts you to the pre-commit state of things.

INSTALLSTRIPPEDMODULES=1

    The installed modules will be stripped of debug info.  The kernel will
    be left with debug info intact.

What this means is that developres will no longer have to stuff a debug
kernel off somewhere to use later instead of a crash, savecore will copy
a debuggable kernel into /var/crash instead of a stripped kernel, and
snapshot and release CD's will have debug kernels and working crash dumps
right out of the box.  The memory impact of the debug kernel is zero since
the debug info is not loaded, and the run-time impact of this change is
also zero.

The intention is multi-fold:

    * To make it easier for inexperienced users to provide meaningful debug
      info to developers when posting bug reports, especially during release
      cycles.

    * To not have to make copies of debug kernels for debugging purposes.
      Such copies often get out of sync with the actually running kernel
      and savecore does not know about them.

    * To make the debugging environment more uniform, less confusing, and
      easier to use.

diff --git a/Makefile.inc1 b/Makefile.inc1
--- a/Makefile.inc1
+++ b/Makefile.inc1
@@ -1,6 +1,6 @@
 #
 # $FreeBSD: src/Makefile.inc1,v 1.141.2.62 2003/04/06 19:54:00 dwmalone Exp $
-# $DragonFly: src/Makefile.inc1,v 1.39 2004/09/28 20:56:38 joerg Exp $
+# $DragonFly: src/Makefile.inc1,v 1.40 2004/10/20 23:02:59 dillon Exp $
 #
 # Make command line options:
 #	-DMAKE_KERBEROS5 to build Kerberos5
@@ -465,6 +465,12 @@ redistribute:
 # for building kernels and only the first of these is designated
 # as the one being installed.
 #
+# You can specify INSTALLSTRIPPED=1 if you wish the installed 
+# kernel and modules to be stripped of its debug info (required
+# symbols are left intact).  You can specify INSTALLSTRIPPEDMODULES
+# if you only want to strip the modules of their debug info.  These
+# only apply if you have DEBUG=-g in your kernel config or make line.
+#
 # Note that we have to use TARGET instead of TARGET_ARCH when
 # we're in kernel-land. Since only TARGET_ARCH is (expected) to
 # be set to cross-build, we have to make sure TARGET is set
@@ -505,7 +511,18 @@ bk_tools:
 	    echo "to build a kernel using native tools, config it manually"; \
 	    echo "or use the nativekernel target if you are in a rush"; \
 	    exit 1; \
-	    fi
+	fi
+
+maybe_bk_tools:
+.for _kernel in ${BUILDKERNELS}
+	@if [ ! -f ${KRNLOBJDIR}/${_kernel}/.nativekernel_run ]; then \
+	    if [ ! -f ${WORLDDEST}/.libraries_done ]; then \
+		echo "The kernel was build using buildworld tools which no" ; \
+		echo "longer appear to exist, quickkernel failed!" ; \
+		exit 1; \
+	    fi; \
+	fi
+.endfor
 
 bk_build_list:
 .if empty(BUILDKERNELS)
@@ -606,7 +623,7 @@ nativekernel:	bk_build_list bk_kernwarn
 # nativekernel.  Config is rerun but the object hierarchy is not rebuilt,
 # nor is the make depend step run.
 #
-quickkernel:	bk_tools bk_build_list bk_kernwarn
+quickkernel:	maybe_bk_tools bk_build_list bk_kernwarn
 .for _kernel in ${BUILDKERNELS}
 	@echo "--------------------------------------------------------------"
 	@echo ">>> Kernel build for ${_kernel} started on `LC_ALL=C date`"
@@ -641,8 +658,13 @@ quickkernel:	bk_tools bk_build_list bk_kernwarn
 # Install the kernel defined by INSTALLKERNEL
 #
 installkernel reinstallkernel:
+.if exists(${KRNLOBJDIR}/${_kernel}/.buildkernel_run)
 	cd ${KRNLOBJDIR}/${INSTALLKERNEL}; \
 	    ${CROSSENV} ${MAKE} KERNEL=${INSTKERNNAME} ${.TARGET:S/kernel$//}
+.else
+	cd ${KRNLOBJDIR}/${INSTALLKERNEL}; \
+	    ${MAKE} KERNEL=${INSTKERNNAME} ${.TARGET:S/kernel$//}
+.endif
 
 #
 # update
