initrd: Support to specify a PFS label in 'vfs.root.realroot'
The 'vfs.root.realroot' syntax previously didn't support to specify a
PFS label for a HAMMER/HAMMER2 filesystem on an encrypted partition.
There was a hack to work around this limitation by naming the mapped
device with 'd' in the end (e.g., use 'rootd' rather than 'root'), so
the kernel would auto mount the '@ROOT' PFS from it.

However, it was impossible to work around the limitation when the target
PFS uses a custom label, e.g., '@ROOT.20260616'.

This commit fixes the limitation by extending the rcmount_{crypt,tcplay}
scripts to support to directly specify the PFS label in
'vfs.root.realroot'.

Update and improve the initrd(7) man page accordingly.

Reported-by: vjkarbo (via IRC)

diff --git a/initrd/etc/rcmount_crypt b/initrd/etc/rcmount_crypt
--- a/initrd/etc/rcmount_crypt
+++ b/initrd/etc/rcmount_crypt
@@ -1,19 +1,29 @@
 #!/bin/sh
 
 FSTYPE=$2
-MOUNTFROM="/dev/${3#/dev/}"
+DEVICE="/dev/${3#/dev/}"
 VOLUME=$4
 OPTIONS=$5
 
-cryptsetup isLuks $MOUNTFROM || {
-	echo "ERROR: not a LUKS device: $MOUNTFROM"
+# Handle the PFS label of a HAMMER/HAMMER2 filesystem.
+LABEL=
+case $DEVICE in
+*@*)
+	LABEL="@${DEVICE#*@}"
+	DEVICE=${DEVICE%@*}
+	;;
+esac
+MOUNTFROM="/dev/mapper/${VOLUME}${LABEL}"
+
+cryptsetup isLuks $DEVICE || {
+	echo "ERROR: not a LUKS device: $DEVICE"
 	return 1
 }
-cryptsetup $OPTIONS luksOpen $MOUNTFROM $VOLUME || {
-	echo "ERROR: failed to open LUKS device: $MOUNTFROM"
+cryptsetup $OPTIONS luksOpen $DEVICE $VOLUME || {
+	echo "ERROR: failed to open LUKS device: $DEVICE"
 	return 2
 }
-mount -o ro -t $FSTYPE /dev/mapper/$VOLUME $NEW_ROOT || {
-	echo "ERROR: failed to mount $FSTYPE from /dev/mapper/$VOLUME"
+mount -o ro -t $FSTYPE $MOUNTFROM $NEW_ROOT || {
+	echo "ERROR: failed to mount $FSTYPE from $MOUNTFROM"
 	return 3
 }
diff --git a/initrd/etc/rcmount_tcplay b/initrd/etc/rcmount_tcplay
--- a/initrd/etc/rcmount_tcplay
+++ b/initrd/etc/rcmount_tcplay
@@ -1,15 +1,25 @@
 #!/bin/sh
 
 FSTYPE=$2
-MOUNTFROM="/dev/${3#/dev/}"
+DEVICE="/dev/${3#/dev/}"
 VOLUME=$4
 OPTIONS=$5
 
-tcplay -m $VOLUME -d $MOUNTFROM $OPTIONS || {
-	echo "ERROR: failed to open tcplay device: $MOUNTFROM"
+# Handle the PFS label of a HAMMER/HAMMER2 filesystem.
+LABEL=
+case $DEVICE in
+*@*)
+	LABEL="@${DEVICE#*@}"
+	DEVICE=${DEVICE%@*}
+	;;
+esac
+MOUNTFROM="/dev/mapper/${VOLUME}${LABEL}"
+
+tcplay -m $VOLUME -d $DEVICE $OPTIONS || {
+	echo "ERROR: failed to open tcplay device: $DEVICE"
 	return 2
 }
-mount -o ro -t $FSTYPE /dev/mapper/$VOLUME $NEW_ROOT || {
-	echo "ERROR: failed to mount $FSTYPE from /dev/mapper/$VOLUME"
+mount -o ro -t $FSTYPE $MOUNTFROM $NEW_ROOT || {
+	echo "ERROR: failed to mount $FSTYPE from $MOUNTFROM"
 	return 3
 }
