initrd: Update rcmount_* scripts to report more error info

diff --git a/initrd/etc/rcmount_crypt b/initrd/etc/rcmount_crypt
--- a/initrd/etc/rcmount_crypt
+++ b/initrd/etc/rcmount_crypt
@@ -5,6 +5,15 @@ MOUNTFROM="/dev/${3#/dev/}"
 VOLUME=$4
 OPTIONS=$5
 
-cryptsetup isLuks $MOUNTFROM || return 1
-cryptsetup $OPTIONS luksOpen $MOUNTFROM $VOLUME || return 2
-mount -o ro -t $FSTYPE /dev/mapper/$VOLUME $NEW_ROOT || return 3
+cryptsetup isLuks $MOUNTFROM || {
+	echo "ERROR: not a LUKS device: $MOUNTFROM"
+	return 1
+}
+cryptsetup $OPTIONS luksOpen $MOUNTFROM $VOLUME || {
+	echo "ERROR: failed to open LUKS device: $MOUNTFROM"
+	return 2
+}
+mount -o ro -t $FSTYPE /dev/mapper/$VOLUME $NEW_ROOT || {
+	echo "ERROR: failed to mount $FSTYPE from /dev/mapper/$VOLUME"
+	return 3
+}
diff --git a/initrd/etc/rcmount_tcplay b/initrd/etc/rcmount_tcplay
--- a/initrd/etc/rcmount_tcplay
+++ b/initrd/etc/rcmount_tcplay
@@ -5,5 +5,11 @@ MOUNTFROM="/dev/${3#/dev/}"
 VOLUME=$4
 OPTIONS=$5
 
-tcplay -m $VOLUME -d $MOUNTFROM $OPTIONS || return 2
-mount -o ro -t $FSTYPE /dev/mapper/$VOLUME $NEW_ROOT || return 3
+tcplay -m $VOLUME -d $MOUNTFROM $OPTIONS || {
+	echo "ERROR: failed to open tcplay device: $MOUNTFROM"
+	return 2
+}
+mount -o ro -t $FSTYPE /dev/mapper/$VOLUME $NEW_ROOT || {
+	echo "ERROR: failed to mount $FSTYPE from /dev/mapper/$VOLUME"
+	return 3
+}
