* Added tabs instead of spaces for readability and consistency with NetBSD    and FreeBSD.

diff --git a/etc/rc.d/accounting b/etc/rc.d/accounting
--- a/etc/rc.d/accounting
+++ b/etc/rc.d/accounting
@@ -2,7 +2,7 @@
 #
 # $NetBSD: accounting,v 1.7 2002/03/22 04:33:57 thorpej Exp $
 # $FreeBSD: src/etc/rc.d/accounting,v 1.4 2002/10/12 10:31:31 schweikh Exp $
-# $DragonFly: src/etc/rc.d/accounting,v 1.1 2003/07/24 06:35:37 dillon Exp $
+# $DragonFly: src/etc/rc.d/accounting,v 1.2 2003/11/19 10:32:45 eirikn Exp $
 #
 
 # PROVIDE: accounting
@@ -24,16 +24,16 @@ accounting_start()
 	case ${OSTYPE} in
 	DragonFly)
 		_dir=`dirname "$accounting_file"`
-                if [ ! -d `dirname "$_dir"` ]; then
-                        if ! mkdir -p "$_dir"; then
-                                warn "Could not create $_dir."
-                                return 1
-                        fi
-                fi
-                if [ ! -e "$accounting_file" ]; then
-                        touch "$accounting_file"
-                fi
-                ;;
+		if [ ! -d `dirname "$_dir"` ]; then
+			if ! mkdir -p "$_dir"; then
+				warn "Could not create $_dir."
+				return 1
+			fi
+		fi
+		if [ ! -e "$accounting_file" ]; then
+			touch "$accounting_file"
+		fi
+		;;
 	FreeBSD) 
 		_dir=`dirname "$accounting_file"`
 		if [ ! -d `dirname "$_dir"` ]; then
diff --git a/etc/rc.d/fsck b/etc/rc.d/fsck
--- a/etc/rc.d/fsck
+++ b/etc/rc.d/fsck
@@ -2,7 +2,7 @@
 #
 # $NetBSD: fsck,v 1.2 2001/06/18 06:42:35 lukem Exp $
 # $FreeBSD: src/etc/rc.d/fsck,v 1.4 2002/10/12 10:31:31 schweikh Exp $
-# $DragonFly: src/etc/rc.d/fsck,v 1.1 2003/07/24 06:35:37 dillon Exp $
+# $DragonFly: src/etc/rc.d/fsck,v 1.2 2003/11/19 10:32:45 eirikn Exp $
 #
 
 # PROVIDE: fsck
@@ -62,22 +62,22 @@ fsck_start()
 		8)
 		case ${OSTYPE} in
 		DragonFly)
-				 if checkyesno fsck_y_enable; then
-                                echo "File system preen failed, trying fsck -y."
-                                fsck -y
-                                case $? in
-                                0)
-                                        ;;
-                                *)
-                                echo "Automatic file system check failed; help!"
-                                        stop_boot
-                                        ;;
-                                esac
-                        else
-                                echo "Automatic file system check failed; help!"
-                                stop_boot
-                        fi
-                        ;;
+			if checkyesno fsck_y_enable; then
+				echo "File system preen failed, trying fsck -y."
+				fsck -y
+				case $? in
+				0)
+					;;
+				*)
+					echo "Automatic file system check failed; help!"
+					stop_boot
+					;;
+				esac
+			else
+				echo "Automatic file system check failed; help!"
+				stop_boot
+			fi
+		;;
 
 		FreeBSD)
 			if checkyesno fsck_y_enable; then
diff --git a/etc/rc.d/ipfilter b/etc/rc.d/ipfilter
--- a/etc/rc.d/ipfilter
+++ b/etc/rc.d/ipfilter
@@ -2,7 +2,7 @@
 #
 # $NetBSD: ipfilter,v 1.10 2001/02/28 17:03:50 lukem Exp $
 # $FreeBSD: src/etc/rc.d/ipfilter,v 1.10 2003/04/30 02:54:17 mtm Exp $
-# $DragonFly: src/etc/rc.d/ipfilter,v 1.1 2003/07/24 06:35:37 dillon Exp $
+# $DragonFly: src/etc/rc.d/ipfilter,v 1.2 2003/11/19 10:32:45 eirikn Exp $
 #
 
 # PROVIDE: ipfilter
@@ -19,7 +19,7 @@ load_rc_config $name
 case ${OSTYPE} in
 DragonFly)
 	stop_precmd="test -f ${ipfilter_rules} -o -f ${ipv6_ipfilter_rules}"
-        ;;
+	;;
 
 FreeBSD)
 	stop_precmd="test -f ${ipfilter_rules} -o -f ${ipv6_ipfilter_rules}"
@@ -45,20 +45,20 @@ ipfilter_prestart()
 case ${OSTYPE} in
 DragonFly)
 	 # load ipfilter kernel module if needed
-        if ! sysctl net.inet.ipf.fr_pass > /dev/null 2>&1; then
-                if kldload ipl; then
-                        info 'IP-filter module loaded.'
-                else
-                        err 1 'IP-filter module failed to load.'
-                fi
-        fi
-        # check for ipfilter rules
-        if [ ! -r "${ipfilter_rules}" ] && [ ! -r "${ipv6_ipfilter_rules}" ]
-        then
-                warn 'IP-filter: NO IPF RULES'
-                return 1
-        fi
-        ;;
+	if ! sysctl net.inet.ipf.fr_pass > /dev/null 2>&1; then
+		if kldload ipl; then
+			info 'IP-filter module loaded.'
+		else
+			err 1 'IP-filter module failed to load.'
+		fi
+	fi
+	# check for ipfilter rules
+	if [ ! -r "${ipfilter_rules}" ] && [ ! -r "${ipv6_ipfilter_rules}" ]
+	then
+		warn 'IP-filter: NO IPF RULES'
+		return 1
+	fi
+	;;
 
 FreeBSD)
 	# load ipfilter kernel module if needed
@@ -101,17 +101,17 @@ ipfilter_start()
 	echo "Enabling ipfilter."
 	case ${OSTYPE} in
 	DragonFly)
-		 ${ipfilter_program:-/sbin/ipf} -EFa
-                if [ -r "${ipfilter_rules}" ]; then
-                        ${ipfilter_program:-/sbin/ipf} \
-                            -f "${ipfilter_rules}" ${ipfilter_flags}
-                fi
-                ${ipfilter_program:-/sbin/ipf} -6 -EFa
-                if [ -r "${ipv6_ipfilter_rules}" ]; then
-                        ${ipfilter_program:-/sbin/ipf} -6 \
-                            -f "${ipv6_ipfilter_rules}" ${ipfilter_flags}
-                fi
-                ;;
+		${ipfilter_program:-/sbin/ipf} -EFa
+		if [ -r "${ipfilter_rules}" ]; then
+			${ipfilter_program:-/sbin/ipf} \
+			-f "${ipfilter_rules}" ${ipfilter_flags}
+		fi
+		${ipfilter_program:-/sbin/ipf} -6 -EFa
+		if [ -r "${ipv6_ipfilter_rules}" ]; then
+			${ipfilter_program:-/sbin/ipf} -6 \
+			-f "${ipv6_ipfilter_rules}" ${ipfilter_flags}
+		fi
+;;
 
 	FreeBSD)
 		${ipfilter_program:-/sbin/ipf} -EFa
@@ -142,8 +142,8 @@ ipfilter_stop()
 	case ${OSTYPE} in
 	DragonFly)
 		echo "Saving firewall state tables"
-                ${ipfs_program:-/sbin/ipfs} -W ${ipfs_flags}
-                ;;
+		${ipfs_program:-/sbin/ipfs} -W ${ipfs_flags}
+		;;
 	FreeBSD)
 		echo "Saving firewall state tables"
 		${ipfs_program:-/sbin/ipfs} -W ${ipfs_flags}
@@ -163,17 +163,17 @@ ipfilter_reload()
 	case ${OSTYPE} in
 	DragonFly)
 		 ${ipfilter_program:-/sbin/ipf} -I -Fa
-                if [ -r "${ipfilter_rules}" ]; then
-                        ${ipfilter_program:-/sbin/ipf} -I \
-                            -f "${ipfilter_rules}" ${ipfilter_flags}
-                fi
-                ${ipfilter_program:-/sbin/ipf} -I -6 -Fa
-                if [ -r "${ipv6_ipfilter_rules}" ]; then
-                        ${ipfilter_program:-/sbin/ipf} -I -6 \
-                            -f "${ipv6_ipfilter_rules}" ${ipfilter_flags}
-                fi
-                ${ipfilter_program:-/sbin/ipf} -s
-                ;;
+		if [ -r "${ipfilter_rules}" ]; then
+			${ipfilter_program:-/sbin/ipf} -I \
+			-f "${ipfilter_rules}" ${ipfilter_flags}
+		fi
+			${ipfilter_program:-/sbin/ipf} -I -6 -Fa
+			if [ -r "${ipv6_ipfilter_rules}" ]; then
+			${ipfilter_program:-/sbin/ipf} -I -6 \
+			-f "${ipv6_ipfilter_rules}" ${ipfilter_flags}
+		fi
+		${ipfilter_program:-/sbin/ipf} -s
+		;;
 	FreeBSD)
 		${ipfilter_program:-/sbin/ipf} -I -Fa
 		if [ -r "${ipfilter_rules}" ]; then
@@ -209,8 +209,8 @@ ipfilter_resync()
 	case ${OSTYPE} in
 	DragonFly)
 		# Don't resync if ipfilter is not loaded
-                [ sysctl net.inet.ipf.fr_pass > /dev/null 2>&1 ] && return
-                ;;
+		[ sysctl net.inet.ipf.fr_pass > /dev/null 2>&1 ] && return
+		;;
 	FreeBSD)
 		# Don't resync if ipfilter is not loaded
 		[ sysctl net.inet.ipf.fr_pass > /dev/null 2>&1 ] && return
diff --git a/etc/rc.d/root b/etc/rc.d/root
--- a/etc/rc.d/root
+++ b/etc/rc.d/root
@@ -2,7 +2,7 @@
 #
 # $NetBSD: root,v 1.2 2000/05/13 08:45:09 lukem Exp $
 # $FreeBSD: src/etc/rc.d/root,v 1.5 2002/10/31 02:06:05 gordon Exp $
-# $DragonFly: src/etc/rc.d/root,v 1.1 2003/07/24 06:35:37 dillon Exp $
+# $DragonFly: src/etc/rc.d/root,v 1.2 2003/11/19 10:32:45 eirikn Exp $
 #
 
 # PROVIDE: root
@@ -20,27 +20,26 @@ root_start()
 	case ${OSTYPE} in
 	DragonFly)
 		# root normally must be read/write, but if this is a BOOTP NFS
-                # diskless boot it does not have to be.
-                #
-                case ${root_rw_mount} in
-                [Nn][Oo] | '')
-                        ;;
-                *)
-                        if ! mount -u -o rw /; then
-                                echo 'Mounting root filesystem rw failed, startup aborted'
-                                exit 1
-                        fi
-                        ;;
-                esac
-                umount -a >/dev/null 2>&1
-                mount /
-                # If we booted a special kernel remove the record
-                # so we will boot the default kernel next time.
-                if [ -e /boot/nextkernel ]; then
-                        rm -f /boot/nextkernel
-                fi
-                ;;
-
+		# diskless boot it does not have to be.
+		#
+		case ${root_rw_mount} in
+		[Nn][Oo] | '')
+			;;
+		*)
+			if ! mount -u -o rw /; then
+				echo 'Mounting root filesystem rw failed, startup aborted'
+				exit 1
+			fi
+			;;
+		esac
+		umount -a >/dev/null 2>&1
+		mount /
+		# If we booted a special kernel remove the record
+		# so we will boot the default kernel next time.
+		if [ -e /boot/nextkernel ]; then
+			rm -f /boot/nextkernel
+		fi
+		;;
 	FreeBSD)
 		# root normally must be read/write, but if this is a BOOTP NFS
 		# diskless boot it does not have to be.
