Adjust nfs module loading to use nfs.ko (4.x style) rather then the separate client/server ko's that 5.x has.
Submitted-by: YONETANI Tomokazu <qhwt@myrealbox.com>

diff --git a/etc/rc.d/nfsclient b/etc/rc.d/nfsclient
--- a/etc/rc.d/nfsclient
+++ b/etc/rc.d/nfsclient
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # $FreeBSD: src/etc/rc.d/nfsclient,v 1.3 2002/10/12 10:31:31 schweikh Exp $
-# $DragonFly: src/etc/rc.d/nfsclient,v 1.2 2003/11/09 07:31:27 dillon Exp $
+# $DragonFly: src/etc/rc.d/nfsclient,v 1.3 2003/11/19 20:11:58 dillon Exp $
 #
 
 # PROVIDE: nfsclient
@@ -20,8 +20,8 @@ stop_cmd="unmount_all"
 nfsclient_precmd()
 {
 	if ! sysctl vfs.nfs >/dev/null 2>&1; then
-		if ! kldload nfsclient; then
-			warn 'Could not load nfs client module'
+		if ! kldload nfs; then
+			warn 'Could not load nfs module'
 			return 1
 		fi
 	fi
diff --git a/etc/rc.d/nfsserver b/etc/rc.d/nfsserver
--- a/etc/rc.d/nfsserver
+++ b/etc/rc.d/nfsserver
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # $FreeBSD: src/etc/rc.d/nfsserver,v 1.2 2002/10/12 10:31:31 schweikh Exp $
-# $DragonFly: src/etc/rc.d/nfsserver,v 1.1 2003/07/24 06:35:37 dillon Exp $
+# $DragonFly: src/etc/rc.d/nfsserver,v 1.2 2003/11/19 20:11:58 dillon Exp $
 #
 
 # PROVIDE: nfsserver
@@ -18,9 +18,9 @@ stop_cmd=":"
 # Load nfs modules if they were not compiled into the kernel
 nfsserver_start()
 {
-	if ! sysctl vfs.nfsrv >/dev/null 2>&1; then
-		if ! kldload nfsserver; then
-			warn 'Could not load NFS server module'
+	if ! sysctl vfs.nfs >/dev/null 2>&1; then
+		if ! kldload nfs; then
+			warn 'Could not load NFS module'
 			return 1
 		fi
 	fi
