update rcng to remove FreeBSD and NetBSD

diff --git a/etc/rc.d/root b/etc/rc.d/root
--- a/etc/rc.d/root
+++ b/etc/rc.d/root
@@ -2,12 +2,12 @@
 #
 # $NetBSD: root,v 1.2 2000/05/13 08:45:09 lukem Exp $
 # $FreeBSD: src/etc/rc.d/root,v 1.5 2002/10/31 02:06:05 gordon Exp $
-# $DragonFly: src/etc/rc.d/root,v 1.2 2003/11/19 10:32:45 eirikn Exp $
+# $DragonFly: src/etc/rc.d/root,v 1.3 2004/01/27 00:42:45 rob Exp $
 #
 
 # PROVIDE: root
 # REQUIRE: fsck
-# KEYWORD: DragonFly FreeBSD NetBSD
+# KEYWORD: DragonFly
 
 . /etc/rc.subr
 
@@ -17,59 +17,26 @@ stop_cmd=":"
 
 root_start()
 {
-	case ${OSTYPE} in
-	DragonFly)
-		# root normally must be read/write, but if this is a BOOTP NFS
-		# diskless boot it does not have to be.
-		#
-		case ${root_rw_mount} in
-		[Nn][Oo] | '')
-			;;
-		*)
-			if ! mount -u -o rw /; then
-				echo 'Mounting root filesystem rw failed, startup aborted'
-				exit 1
-			fi
-			;;
-		esac
-		umount -a >/dev/null 2>&1
-		mount /
-		# If we booted a special kernel remove the record
-		# so we will boot the default kernel next time.
-		if [ -e /boot/nextkernel ]; then
-			rm -f /boot/nextkernel
-		fi
+	# root normally must be read/write, but if this is a BOOTP NFS
+	# diskless boot it does not have to be.
+	#
+	case ${root_rw_mount} in
+	[Nn][Oo] | '')
 		;;
-	FreeBSD)
-		# root normally must be read/write, but if this is a BOOTP NFS
-		# diskless boot it does not have to be.
-		#
-		case ${root_rw_mount} in
-		[Nn][Oo] | '')
-			;;
-		*)
-			if ! mount -u -o rw /; then
-				echo 'Mounting root filesystem rw failed, startup aborted'
-				exit 1
-			fi
-			;;
-		esac
-
-		umount -a >/dev/null 2>&1
-		mount /
-
-		# If we booted a special kernel remove the record
-		# so we will boot the default kernel next time.
-		if [ -e /boot/nextkernel ]; then
-			rm -f /boot/nextkernel
+	*)
+		if ! mount -u -o rw /; then
+			echo 'Mounting root filesystem rw failed, startup aborted'
+			exit 1
 		fi
-		;;
-	NetBSD)
-		umount -a >/dev/null 2>&1
-		mount /
-		rm -f /fastboot
 		;;
 	esac
+	umount -a >/dev/null 2>&1
+	mount /
+	# If we booted a special kernel remove the record
+	# so we will boot the default kernel next time.
+	if [ -e /boot/nextkernel ]; then
+		rm -f /boot/nextkernel
+	fi
 }
 
 load_rc_config $name
