rc.d: Various style and whitespace cleanups
No functional changes.

diff --git a/etc/rc.d/rtadvd b/etc/rc.d/rtadvd
--- a/etc/rc.d/rtadvd
+++ b/etc/rc.d/rtadvd
@@ -17,10 +17,9 @@ start_precmd="rtadvd_precmd"
 
 rtadvd_precmd()
 {
-	IS_GATEWAY="checkyesno ipv6_gateway_enable"
-	if ! ${IS_GATEWAY}; then
-		warn \
-		  "${name} cannot be used on IPv6 host, only on an IPv6 router."
+	if ! checkyesno ipv6_gateway_enable; then
+		warn "${name} cannot be used on IPv6 host, " \
+		     "only on an IPv6 router."
 		return 1
 	fi
 
