Import the new nrelease Makefile packaging and root template infrastructure from the DragonFly Installer Team and make the following additional augmentations:
* Use the default port package install location to retrieve packages.
* Pre-check that all required packages exist before doing anything
* Remove the root autologin (also means that gettytab and ~root/.login can
  be removed from the original template).
* Add an etc/issue file
* Add an 'installer' user (root uid)

Obtained-from: The DragonFly Installer Team:
    Chris Pressey, Devon O'Dell, Eirik Nygaard, Hiten Pandya & GeekGod

diff --git a/nrelease/Makefile b/nrelease/Makefile
--- a/nrelease/Makefile
+++ b/nrelease/Makefile
@@ -1,4 +1,4 @@
-# $DragonFly: src/nrelease/Makefile,v 1.8 2004/04/23 02:14:07 dillon Exp $
+# $DragonFly: src/nrelease/Makefile,v 1.9 2004/07/10 22:29:11 dillon Exp $
 #
 
 ISODIR ?= /usr/release
@@ -6,6 +6,21 @@ ISOFILE ?= ${ISODIR}/dfly.iso
 ISOROOT = ${ISODIR}/root
 OBJSYS= ${.OBJDIR}/../sys
 KERNCONF ?= GENERIC
+
+# Specify which packages are required on the ISO, and let the user
+# specify additional packages to include.  During the `pkgaddiso'
+# target, the packages are obtained from PACKAGES_LOC.
+#
+REQ_PACKAGES= cdrtools-2.0.3_3 cvsup-without-gui-16.1h
+PACKAGES?= ${REQ_PACKAGES} ${EXTRA_PACKAGES}
+PACKAGES_LOC?= /usr/ports/packages/All
+
+# Specify which root skeletons are required, and let the user include
+# their own.  They are copied into ISODIR during the `pkgcustomizeiso'
+# target; each overwrites the last.
+#
+REQ_ROOTSKELS= ${.CURDIR}/root
+ROOTSKELS?= ${REQ_ROOTSKELS} ${EXTRA_ROOTSKELS}
 
 # note: we use the '${NRLOBJDIR}/nrelease' construct, that is we add
 # the additional '/nrelease' manually, as a safety measure.
@@ -15,19 +30,64 @@ NRLOBJDIR?= /usr/obj
 WORLD_CCVER ?= ${CCVER}
 KERNEL_CCVER ?= ${CCVER}
 
-release:	check clean buildworld1 buildkernel1 buildiso mkiso
+#########################################################################
+#				BASE ISO TARGETS 			#
+#########################################################################
 
-quickrel:	check clean buildworld2 buildkernel2 buildiso mkiso
+release:	check clean buildworld1 buildkernel1 \
+		buildiso customizeiso pkgaddiso mkiso
 
-realquickrel:	check clean buildiso mkiso
+quickrel:	check clean buildworld2 buildkernel2 \
+		buildiso customizeiso pkgaddiso mkiso
+
+realquickrel:	check clean \
+		buildiso customizeiso pkgaddiso mkiso
+
+#########################################################################
+#			ISO TARGETS WITH INSTALLER			#
+#########################################################################
+
+INSTALLER_PKGS= dfuibe_installer dfuife_curses libdfui \
+		thttpd-notimeout dfuife_cgi
+INSTALLER_SKELS= installer
+
+INSTALLER_ENV= EXTRA_PACKAGES="${INSTALLER_PKGS}" \
+		EXTRA_ROOTSKELS="${INSTALLER_SKELS}"
+
+installer_check:
+		@${INSTALLER_ENV} ${MAKE} check
+
+installer_release:
+		${INSTALLER_ENV} ${MAKE} release
+
+installer_quickrel:
+		${INSTALLER_ENV} ${MAKE} quickrel
+
+installer_realquickrel:
+		${INSTALLER_ENV} ${MAKE} realquickrel
+
+#########################################################################
+#				HELPER TARGETS				#
+#########################################################################
 
 check:
-	if [ ! -f /usr/local/bin/mkisofs ]; then \
+	@if [ ! -f /usr/local/bin/mkisofs ]; then \
 		echo "You need to install the mkisofs port for this target"; \
-		exit 1; fi
-	if [ ! -f /usr/local/bin/cvsup ]; then \
-		echo "You need to install the cvsup port for this target"; \
-		exit 1; fi
+		exit 1; \
+	fi
+.for PKG in ${PACKAGES}
+	@if [ ! -f ${PACKAGES_LOC}/${PKG}.tgz ]; then \
+		echo "Unable to find ${PACKAGES_LOC}/${PKG}.tgz.  This is"; \
+		echo "typically accomplished by cd'ing into the appropriate"; \
+		echo "port and typing 'make package'"; \
+		echo ""; \
+		echo "If you are trying to build the installer, the"; \
+		echo "required packages can be obtained from:"; \
+		echo "http://catseye.mine.nu:8080/DragonFlyBSD/installer/"; \
+		exit 1; \
+	fi
+.endfor
+	@echo "check: all preqs found"
 
 buildworld1:
 	( cd ${.CURDIR}/..; make buildworld CCVER=${WORLD_CCVER} )
@@ -51,16 +111,42 @@ buildiso:
 	if [ ! -d ${NRLOBJDIR}/nrelease ]; then mkdir -p ${NRLOBJDIR}/nrelease; fi
 	( cd ${.CURDIR}/..; make DESTDIR=${ISOROOT} installworld )
 	( cd ${.CURDIR}/../etc; MAKEOBJDIRPREFIX=${NRLOBJDIR}/nrelease make DESTDIR=${ISOROOT} distribution )
-	cpdup -X cpignore -o ${.CURDIR}/root ${ISOROOT} -vv
 	( cd ${.CURDIR}/..; make DESTDIR=${ISOROOT} \
 		installkernel KERNCONF=${KERNCONF} )
 	mtree -deU -f ${.CURDIR}/../etc/mtree/BSD.local.dist -p ${ISOROOT}/usr/local/
 	mtree -deU -f ${.CURDIR}/../etc/mtree/BSD.var.dist -p ${ISOROOT}/var
 	dev_mkdb -f ${ISOROOT}/var/run/dev.db ${ISOROOT}/dev
-	cp /usr/local/bin/mkisofs ${ISOROOT}/usr/local/bin
-	cp /usr/local/man/man8/mkisofs.8.gz ${ISOROOT}/usr/local/man/man8
-	cp /usr/local/bin/cvsup ${ISOROOT}/usr/local/bin
-	cp /usr/local/man/man1/cvsup.1.gz ${ISOROOT}/usr/local/man/man1
+
+customizeiso:
+.for ROOTSKEL in ${ROOTSKELS}
+	cpdup -X cpignore -o ${ROOTSKEL} ${ISOROOT}
+.endfor
+	rm -rf `find ${ISOROOT} -type d -name CVS -print`
+
+pkgcleaniso:
+	rm -f ${ISOROOT}/tmp/chrootscript
+	echo "#!/bin/sh" > ${ISOROOT}/tmp/chrootscript
+.for PKG in ${PACKAGES}
+	echo "pkg_delete -f ${PKG}" >> ${ISOROOT}/tmp/chrootscript
+.endfor
+	chmod a+x ${ISOROOT}/tmp/chrootscript
+	chroot ${ISOROOT}/ /tmp/chrootscript || exit 0
+	rm ${ISOROOT}/tmp/chrootscript
+
+pkgaddiso:
+	rm -f ${ISOROOT}/tmp/chrootscript
+	echo "#!/bin/sh" > ${ISOROOT}/tmp/chrootscript
+.for PKG in ${PACKAGES}
+	cp ${PACKAGES_LOC}/${PKG}.tgz ${ISOROOT}/tmp/${PKG}.tgz
+	echo "echo 'Installing package ${PKG}...'" >> ${ISOROOT}/tmp/chrootscript
+	echo "pkg_add /tmp/${PKG}.tgz" >> ${ISOROOT}/tmp/chrootscript
+.endfor
+	chmod a+x ${ISOROOT}/tmp/chrootscript
+	chroot ${ISOROOT}/ /tmp/chrootscript
+	rm ${ISOROOT}/tmp/chrootscript
+.for PKG in ${PACKAGES}
+	rm -f ${ISOROOT}/tmp/${PKG}.tgz
+.endfor
 
 mkiso:
 	( cd ${ISOROOT}; mkisofs -b boot/cdboot -no-emul-boot \
@@ -68,7 +154,7 @@ mkiso:
 
 clean:
 	if [ -d ${ISOROOT} ]; then chflags -R noschg ${ISOROOT}; fi
-	if [ -d ${ISOROOT} ]; then rm -rf ${ISOROOT}; fi
+	if [ -d ${ISOROOT} ]; then rm -rf ${ISOROOT}/*; fi
 	if [ -d ${NRLOBJDIR}/nrelease ]; then rm -rf ${NRLOBJDIR}/nrelease; fi
 
 realclean:	clean
