Update gzip.
- gzexe: Ensure we do not compress files we need for decompressing by
also checking hard links. From Andrew Dalgleish. (from OpenBSD)
- note that -n also stops the timestamp from being output.
- Don't abort decompression if there are no bytes in the output buffer
when the end of compressed block (ie the crc) is reached.
(ie when decompressing concatenated zipped files).
- If stdin is the input stream, fstat it and check if it's
file. If so, use it's mtime for the mtime in the header. Otherwise use
time(2)'s result instead. Lines up with GNU gzip and RFC 1952 now as
well.
- Fix parsing of $GZIP so that not to overrun the end of string.
- handle partial reads.
- avoid an infinite loop while decompressing invalid gzip files.
- in file_compress() always stat() the input file.  this patch avoids
reading from uninitialised space.
- Fix a few issues:
 gzip -vt just prints the contents of a .Z file
 gzip -vt will print OK even if the .gz file is corrupt
 gzip -vt prints nothing with a .bz2 file
 gzip can loop endlessly with a corrupt .bz2 file
- Don't warn about >4GB files not having their size correctly stored.
- Remove unhandled H option from getopt() argument. Describe -l in usage.
- properly check the return value of read() & pread().
- Delete impossible code.
- Abort decompression with an error when EOF is reached on input. The
test output will then be 'NOT OK'.
- End a decompression when trailing garbage is found. It emits a warning
message and causes a non-zero exit status (similar to GNU gzip).
- properly detect when the output fails (eg, full filesystem) and do not
delete the input file.

Dragonfly-bug: http://bugs.dragonflybsd.org/issue1026

diff --git a/usr.bin/gzip/zgrep b/usr.bin/gzip/zgrep
--- a/usr.bin/gzip/zgrep
+++ b/usr.bin/gzip/zgrep
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $NetBSD: zgrep,v 1.3 2004/04/27 09:18:16 jdolecek Exp $
+# $NetBSD: zgrep,v 1.7 2008/05/08 15:35:23 wiz Exp $
 # $DragonFly: src/usr.bin/gzip/zgrep,v 1.1 2004/10/26 11:19:31 joerg Exp $
 #
 # Copyright (c) 2003 Thomas Klausner.
@@ -13,8 +13,6 @@
 # 2. Redistributions in binary form must reproduce the above copyright
 #    notice, this list of conditions and the following disclaimer in the
 #    documentation and/or other materials provided with the distribution.
-# 3. The name of the author may not be used to endorse or promote products
-#    derived from this software without specific prior written permission.
 #
 # THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 # IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
@@ -33,6 +31,8 @@ zcat=/usr/bin/zcat
 endofopts=0
 pattern_found=0
 grep_args=""
+hyphen=0
+silent=0
 
 prg=$0
 
@@ -52,28 +52,35 @@ do
     case $1 in
     # from GNU grep-2.5.1 -- keep in sync!
 	-[ABCDXdefm])
+	    if [ $# -lt 2 ]
+		then
+		echo "${prg}: missing argument for $1 flag" >&2
+		exit 1
+	    fi
 	    case $1 in
 		-e)
-		    pattern_found=1;;
+		    pattern="$2"
+		    pattern_found=1
+		    shift 2
+		    break
+		    ;;
 		*)
 		    ;;
 	    esac
-
-	    if [ $# -lt 2 ]
-		then
-		echo "${prg}: missing argument for ${saved_arg} flag" >&2
-		exit 1
-	    fi
 	    grep_args="${grep_args} $1 $2"
 	    shift 2
 	    ;;
 	--)
-	    grep_args="${grep_args} $1"
 	    shift
 	    endofopts=1
 	    ;;
 	-)
-	    endofopts=1
+	    hyphen=1
+	    shift
+	    ;;
+	-h)
+	    silent=1
+	    shift
 	    ;;
 	-*)
 	    grep_args="${grep_args} $1"
@@ -89,25 +96,30 @@ done
 # if no -e option was found, take next argument as grep-pattern
 if [ ${pattern_found} -lt 1 ]
 then
-    if [ $# -lt 1 ]
-    then
+    if [ $# -ge 1 ]; then
+	pattern="$1"
+	shift
+    elif [ ${hyphen} -gt 0 ]; then
+	pattern="-"
+    else
 	echo "${prg}: missing pattern" >&2
 	exit 1
     fi
-    pattern=$1
-    shift
 fi
 
 # call grep ...
 if [ $# -lt 1 ]
 then
     # ... on stdin
-    ${zcat} -fq - | ${grep} ${grep_args} "${pattern}" -
+    ${zcat} -fq - | ${grep} ${grep_args} -- "${pattern}" -
 else
     # ... on all files given on the command line
+    if [ ${silent} -lt 1 ]; then
+	grep_args="-H ${grep_args}"
+    fi
     while [ $# -gt 0 ]
     do
-	${zcat} -fq -- "$1" | ${grep} -H --label="${1}" "${pattern}" ${grep_args} -
+	${zcat} -fq -- "$1" | ${grep} --label="${1}" ${grep_args} -- "${pattern}" -
 	shift
     done
 fi
